/**
 * Parse a FactorLab HTML tearsheet and extract key fields for verification.
 *
 * The tearsheet structure is generated by lib/report-builder.ts.
 * Key structural patterns:
 *   - <div class="meta"> contains run identity fields as <p> elements
 *   - <div class="kpi"> elements contain .label and .value children
 *   - Chart date labels are in <div style="...justify-content:space-between...">
 *   - The title is <h1>Strategy Tearsheet</h1>
 */

export type ParsedReport = {
  // Identity
  runName: string | null
  strategyLabel: string | null
  strategyId: string | null
  benchmark: string | null
  window: string | null       // "2019-01-01 to 2025-03-14"
  universe: string | null
  rebalanceFreq: string | null
  topN: string | null
  costs: string | null
  modelImpl: string | null
  modelVersion: string | null
  featureSet: string | null

  // KPIs
  cagr: string | null
  sharpe: string | null
  maxDrawdown: string | null
  volatility: string | null
  winRate: string | null
  profitFactor: string | null
  turnover: string | null
  calmar: string | null

  // Chart date labels (start, mid, end)
  chartStartLabel: string | null
  chartMidLabel: string | null
  chartEndLabel: string | null

  // Equity curve summary
  startNav: string | null
  endNav: string | null
  benchmarkEnd: string | null

  // Overlap / dual-class warnings
  benchmarkOverlapDetected: boolean
  dualClassDetected: boolean

  // Encoding check
  rawTextSnippet: string

  // Parsing errors
  parseErrors: string[]
}

export function parseReportHtml(html: string): ParsedReport {
  const errors: string[] = []

  function extractMeta(label: string): string | null {
    // Matches: <p><strong>Run:</strong> Some Value</p>
    // Also: <p><strong>Run:</strong> Some Value <span ...>...</span></p>
    const re = new RegExp(`<strong>${escapeRe(label)}:</strong>\\s*([^<]+)`, "i")
    const m = html.match(re)
    if (!m) return null
    return decodeEntities(m[1].trim())
  }

  function extractKpi(label: string): string | null {
    // Structure: <div class="kpi"><div class="label">CAGR</div><div class="value">12.3%</div></div>
    const re = new RegExp(
      `<div class="label">${escapeRe(label)}<\\/div>\\s*<div class="value">([^<]+)<\\/div>`,
      "i"
    )
    const m = html.match(re)
    if (!m) return null
    return decodeEntities(m[1].trim())
  }

  // ── Identity ──────────────────────────────────────────────────────────────

  const runName = extractMeta("Run")
  const strategyRaw = extractMeta("Strategy")
  // "Momentum 12-1 (momentum_12_1)" → split on last ( ... )
  let strategyLabel: string | null = null
  let strategyId: string | null = null
  if (strategyRaw) {
    const m = strategyRaw.match(/^(.+?)\s*\(([^)]+)\)\s*$/)
    if (m) {
      strategyLabel = m[1].trim()
      strategyId = m[2].trim()
    } else {
      strategyLabel = strategyRaw
    }
  }

  const benchmark = extractMeta("Benchmark")
  const window = extractMeta("Window")
  const universeRaw = extractMeta("Universe")
  const rebalanceFreq = extractMeta("Rebalance frequency")
  const topN = extractMeta("Top N")
  const costs = extractMeta("Transaction costs")
  const modelImpl = extractMeta("Model impl")
  const modelVersion = extractMeta("Model version")
  const featureSet = extractMeta("Feature set")

  // ── KPIs ──────────────────────────────────────────────────────────────────

  const cagr = extractKpi("CAGR")
  const sharpe = extractKpi("Sharpe")
  // Max Drawdown label includes "(peak-to-trough)"
  const maxDrawdown = extractKpi("Max Drawdown (peak-to-trough)") ?? extractKpi("Max Drawdown")
  const volatility = extractKpi("Volatility")
  const winRate = extractKpi("Win Rate")
  const profitFactor = extractKpi("Profit Factor")
  const turnover = extractKpi("Turnover")
  const calmar = extractKpi("Calmar")

  // ── Chart date labels ─────────────────────────────────────────────────────
  // Pattern: <div style="display:flex;justify-content:space-between;...">
  //            <span>2019-01-02</span><span>2022-01-14</span><span>2025-03-07</span>
  //          </div>
  let chartStartLabel: string | null = null
  let chartMidLabel: string | null = null
  let chartEndLabel: string | null = null

  const xAxisRe = /display:flex;justify-content:space-between[^>]*>(.+?)<\/div>/gs
  const xAxisMatches = [...html.matchAll(xAxisRe)]
  if (xAxisMatches.length > 0) {
    // First x-axis block is the equity chart
    const firstBlock = xAxisMatches[0][1]
    const spans = [...firstBlock.matchAll(/<span>([^<]+)<\/span>/g)]
    if (spans.length >= 1) chartStartLabel = decodeEntities(spans[0][1].trim())
    if (spans.length >= 2) chartMidLabel = decodeEntities(spans[1][1].trim())
    if (spans.length >= 3) chartEndLabel = decodeEntities(spans[2][1].trim())
  } else {
    errors.push("Could not find chart x-axis date labels")
  }

  // ── Equity curve summary ──────────────────────────────────────────────────
  // Pattern: <p><strong>Start NAV:</strong> $100,000 | <strong>End NAV:</strong> $145,000</p>
  let startNav: string | null = null
  let endNav: string | null = null
  let benchmarkEnd: string | null = null

  const navRe = /<strong>Start NAV:<\/strong>\s*([^|<]+)\|?\s*<strong>End NAV:<\/strong>\s*([^<]+)/i
  const navMatch = html.match(navRe)
  if (navMatch) {
    startNav = decodeEntities(navMatch[1].trim())
    endNav = decodeEntities(navMatch[2].trim())
  } else {
    errors.push("Could not find Start NAV/End NAV in tearsheet")
  }

  const benchEndRe = /<strong>Benchmark End:<\/strong>\s*([^<]+)/i
  const benchEndMatch = html.match(benchEndRe)
  if (benchEndMatch) {
    benchmarkEnd = decodeEntities(benchEndMatch[1].trim())
  }

  // ── Overlap / dual-class ──────────────────────────────────────────────────
  const benchmarkOverlapDetected = html.includes("portfolio holds") && html.includes("at some rebalances")
  const dualClassDetected = html.includes("dual-class shares") || html.includes("Dual-class shares")

  // ── Encoding check ────────────────────────────────────────────────────────
  // Grab a sample of text from the meta section for encoding verification
  const metaMatch = html.match(/<div class="meta">(.{0,500})/s)
  const rawTextSnippet = metaMatch ? metaMatch[1].replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim() : ""

  // Check for common mojibake
  if (/\u00c3[\u0080-\u00ff]|â€[\u2122\u0153\u201c\u201d]|\uFFFD/.test(html)) {
    errors.push("Possible mojibake/encoding corruption detected in tearsheet HTML")
  }

  // Check for raw Unicode chars that should be entities
  if (/[÷×—]/.test(html.slice(0, 50_000))) {
    // Could be intentional in some contexts — flag as a warning, not an error
    errors.push("Raw Unicode chars found (÷ × —) — verify these are intentional and not mojibake")
  }

  // Validate KPIs are present
  for (const [name, val] of [
    ["CAGR", cagr], ["Sharpe", sharpe], ["Max Drawdown", maxDrawdown],
    ["Volatility", volatility], ["Win Rate", winRate], ["Profit Factor", profitFactor],
    ["Turnover", turnover], ["Calmar", calmar],
  ]) {
    if (!val) errors.push(`Missing KPI in tearsheet: ${name}`)
  }

  return {
    runName,
    strategyLabel,
    strategyId,
    benchmark,
    window,
    universe: universeRaw,
    rebalanceFreq,
    topN,
    costs,
    modelImpl,
    modelVersion,
    featureSet,
    cagr,
    sharpe,
    maxDrawdown,
    volatility,
    winRate,
    profitFactor,
    turnover,
    calmar,
    chartStartLabel,
    chartMidLabel,
    chartEndLabel,
    startNav,
    endNav,
    benchmarkEnd,
    benchmarkOverlapDetected,
    dualClassDetected,
    rawTextSnippet,
    parseErrors: errors,
  }
}

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
}

function decodeEntities(s: string): string {
  return s
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&mdash;/g, "—")
    .replace(/&divide;/g, "÷")
    .replace(/&times;/g, "×")
    .replace(/&nbsp;/g, " ")
}
